#ifndef CERTALATOR_H
#define CERTALATOR_H

#define CERTALATOR_MAX_SUBJET_LENGTH 1024
#define CERTALATOR_MAX_SAN_LENGTH    512
#define CERTALATOR_MAX_SANS          16
#define CERTALATOR_MAX_ROLE_LENGTH   64
#define CERTALATOR_MAX_ROLES         256

#endif
