#!/bin/sh

set -e

export PATH=$PATH:.

if [ -z "$USE_VALGRIND" ]; then
	USE_VALGRIND=no
fi
if [ -z "$DBG_DELAY" ]; then
	DBG_DELAY=0
fi
if [ -d testdata ]; then
	rm -rf testdata
fi
mkdir -p testdata
basedir=`realpath testdata`
cnf=`realpath openssl.cnf`
if [ -z "$MDRD" ]; then
	MDRD=mdrd
fi

uid=`whoami`

fail()
{
	echo "$(basename $0): $@" >&2
	exit 1
}

cleanup()
{
	[ -f $basedir/authority1/mdrd.pid ] && \
		kill `cat $basedir/authority1/mdrd.pid`
	[ -f $basedir/client3/mdrd.pid ] && \
		kill `cat $basedir/client3/mdrd.pid`
}

trap cleanup TERM INT EXIT

./setup_ca.sh -s $cnf -d $basedir -O Example -D example.com setup-root

#
# Authority setup
#
mkdir -p $basedir/authority1/certdb
cat << EOF > $basedir/authority1/certes.conf
enable_coredumps = true
authority_fqdn = "localhost"
authority_port = 9792
certdb_path = "$basedir/authority1/certdb/certdb.sqlite"
certdb_backup_path = "$basedir/authority1/certdb/certdb.sqlite.bk"
certdb_backup_interval_seconds = 60
root_cert_file = "$basedir/authority1/root.pem"
crl_path = "$basedir/authority1/crls"
crl_reload_interval_seconds = 30
cert_file = "$basedir/authority1/ca_cert.pem"
key_file = "$basedir/authority1/ca_key.pem"
lock_file = "$basedir/authority1/agent.lock"
agent_socket_path = "$basedir/authority1/agent.sock"
cert_org = "Example"
cert_email = "certes@example.com"
min_serial = "0x1000000"
max_serial = "0x1ffffff"
EOF

cat << EOF > $basedir/authority1/mdrd.conf
uid = $uid
gid = $uid
enable_coredumps = true
ca_file = "$basedir/authority1/root.pem"
crl_path = "$basedir/authority1/crls"
cert_file = "$basedir/authority1/proxy_cert.pem"
key_file = "$basedir/authority1/proxy_key.pem"
require_client_cert = false
crl_scan_interval_sec = 60

port = 9792
listen_backlog = 1024
prefork = 1
pid_file = "$basedir/authority1/mdrd.pid"
counters_sock = "$basedir/authority1/counters.sock"

max_clients = 10000
max_conn_per_ip = 25
use_rcv_lowat = true
so_debug = false
rcvbuf = 0
sndbuf = 0
socket_timeout_min = 3
socket_timeout_max = 300
max_payload_size = 16384
max_cert_size = 4096
dbg_delay_to_backend_seconds = $DBG_DELAY

allowed_mdr_domains = [ 0x00000002 ]

EOF

if [ -x /usr/bin/valgrind -a "$USE_VALGRIND" = "yes" ]; then
	cat << EOF >> $basedir/authority1/mdrd.conf
backend_argv = [
	"/usr/bin/valgrind"
	"--log-file=$basedir/authority1/valgrind.%p.out"
	"--keep-stacktraces=none"
	"--leak-check=full"
	"--track-origins=yes"
	"--show-leak-kinds=definite,possible,indirect"
	"-s"
	"$(realpath certes)"
	"-config"
	"$basedir/authority1/certes.conf"
	"mdrd-backend"
]
EOF
else
	cat << EOF >> $basedir/authority1/mdrd.conf
backend_argv = [
	"$(realpath certes)"
	"-config"
	"$basedir/authority1/certes.conf"
	"mdrd-backend"
]
EOF
fi

cat << EOF >> $basedir/authority1/mdrd.conf
backend_uid = $uid
backend_gid = $uid
backend_promises = "stdio rpath wpath cpath inet flock unix dns proc error"
backend_unveils = [
	"x=$(realpath certes)"
	"r=$basedir/authority1/certes.conf"
	"r=$basedir/authority1/root.pem"
	"r=$basedir/authority1/ca_key.pem"
	"rw=$basedir/authority1/ca_cert.pem"
	"rwc=$basedir/authority1/agent.lock"
	"rwc=$basedir/authority1/agent.sock"
	"rwc=$basedir/authority1/certdb"
	"rwc=$basedir/authority1/crls"
]
EOF

serial=`cat $basedir/ca/serial`
./setup_ca.sh -s $cnf -c $basedir/authority1/certes.conf \
	-d $basedir/authority1 -O Example \
	ca-reqs Authority1 authority1.example.com DNS:authority1.example.com

./setup_ca.sh -y -s $cnf -d $basedir \
	sign-ca-req < $basedir/authority1/ca_req.pem
cp $basedir/ca/root.pem $basedir/authority1/
cp $basedir/ca/certs/$serial.pem $basedir/authority1/ca_cert.pem
mkdir -p $basedir/authority1/crls/
cp $basedir/ca/root.crl $basedir/authority1/crls/

serial=`cat $basedir/ca/serial`
./setup_ca.sh -y -s $cnf -d $basedir \
	sign-proxy-req < $basedir/authority1/proxy_req.pem
cp $basedir/ca/certs/$serial.pem $basedir/authority1/proxy_cert.pem

ulimit -c unlimited
$MDRD -c $basedir/authority1/mdrd.conf

for i in 1 2 3 4 5; do
	nc -vz localhost 9792 >/dev/null 2>&1 && break
	sleep 1
done
echo "* Authority running with pid `cat $basedir/authority1/mdrd.pid`"

#
# Agent setup; make the cert expiry short to force a refresh as well
# as a purge from certs table, for testing
#

./certes -config $basedir/authority1/certes.conf \
	bootstrap-setup -role agent -san DNS:certes.example.com \
	-cert_expiry 300
echo "* Bootstrap setup done"

bootstrap_key=$(sqlite3 $basedir/authority1/certdb/certdb.sqlite \
	"select base64(bootstrap_key) from bootstrap where
	subject = '';")
[ -z "$bootstrap_key" ] && fail "bootstrap key not found"

# client3 will be used to test the full bootstrap process, everything
# is generated by certes; REQ, key and cert bootstrap.
mkdir -p $basedir/client3/crls
cp $basedir/ca/root.crl $basedir/client3/crls/
cp $basedir/ca/root.pem $basedir/client3/

cat << EOF > $basedir/client3/certes.conf
enable_coredumps = true
bootstrap_key = "$bootstrap_key"
authority_fqdn = "localhost"
authority_port = 9792
root_cert_file = "$basedir/client3/root.pem"
crl_path = "$basedir/client3/crls"
crl_reload_interval_seconds = 30
cert_file = "$basedir/client3/cert.pem"
key_file = "$basedir/client3/key.pem"
lock_file = "$basedir/client3/agent.lock"
agent_socket_path = "$basedir/client3/agent.sock"
cert_org = "Example"
cert_email = "cert@example.com"
cert_check_interval_seconds = 30
EOF

./certes -config $basedir/client3/certes.conf init
echo "* Agent initialized"

cat << EOF > $basedir/client3/mdrd.conf
uid = $uid
gid = $uid
enable_coredumps = true
ca_file = "$basedir/client3/root.pem"
crl_path = "$basedir/client3/crls"
cert_file = "$basedir/client3/cert.pem"
key_file = "$basedir/client3/key.pem"
require_client_cert = true
crl_scan_interval_sec = 30

port = 9790
listen_backlog = 1024
prefork = 1
pid_file = "$basedir/client3/mdrd.pid"
counters_sock = "$basedir/client3/counters.sock"

max_clients = 10000
max_conn_per_ip = 25
use_rcv_lowat = true
so_debug = false
rcvbuf = 0
sndbuf = 0
socket_timeout_min = 3
socket_timeout_max = 300
max_payload_size = 16384
max_cert_size = 4096
dbg_delay_to_backend_seconds = $DBG_DELAY

allowed_mdr_domains = [ 0x00000002 ]

backend_argv = [
	"$(realpath certes)"
	"-config"
	"$basedir/client3/certes.conf"
	"mdrd-backend"
]
backend_uid = $uid
backend_gid = $uid
backend_promises = "stdio rpath wpath cpath inet flock unix dns proc error"
backend_unveils = [
	"x=$(realpath certes)"
	"r=$basedir/client3"
	"rwc=$basedir/client3/cert.pem"
	"rwc=$basedir/client3/cert.pem.new"
	"rwc=$basedir/client3/agent.lock"
	"rwc=$basedir/client3/agent.sock"
	"rwc=$basedir/client3/crls"
]
EOF

$MDRD -c $basedir/client3/mdrd.conf
echo "* Agent running with pid `cat $basedir/client3/mdrd.pid`"

echo -n "Press any key to terminate daemon..."
read PAUSE
